# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /opt/dirty/0583-App-zur-Registrierung-Infizierter
          git pull
          python3 -m venv env
          env/bin/pip install --upgrade pip setuptools
          env/bin/pip install -e .
          env/bin/alembic -c production.ini upgrade head
          env/bin/supervisorctl  restart all || true
